# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
s = s.split(" ");
print(s)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
txt = "The diameter of {Planet} is {dia} kilometer.".format(Planet = planet, dia = diameter)
print(txt)

The diameter of Earth is 12742 kilometer.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [2]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
arr = np.zeros(10, dtype = int)
print(arr)

[0 0 0 0 0 0 0 0 0 0]


In [ ]:
arr = np.ones(10, dtype = int)*5
print(arr)

[5 5 5 5 5 5 5 5 5 5]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
arr = np.arange(20, 36, 2)
print(arr)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
arr = np.arange(0, 9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.concatenate((a, b), axis = 0)
print(c)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [3]:
import pandas as pd
d = np.array([[1,2],[3,4],[5,6]])
print(d)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
df = pd.DataFrame(d)
print(df)

   0  1
0  1  2
1  3  4
2  5  6


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import datetime
start = datetime.datetime.strptime("01-01-2023", "%d-%m-%Y")
end = datetime.datetime.strptime("10-02-2023", "%d-%m-%Y")
date_generated = pd.date_range(start, end)
print(date_generated.strftime("%d-%m-%Y"))

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
df = pd.DataFrame(lists)
df

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24